services:

  mysql:
    image: mysql:8.0
    container_name: smart_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: smart_inventory
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - smart_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot1234" ]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: smart_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root1234
      DB_NAME: smart_inventory
      JWT_SECRET: smart_inventory_secret_2024
      JWT_EXPIRES_IN: 24h
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - smart_network

  frontend:
    build: ./frontend
    container_name: smart_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - smart_network

volumes:
  mysql_data:

networks:
  smart_network:
    driver: bridge
